import { mock } from '@src/utils/common';

export const getData = () =>
  mock([
    {
      name: 'SCHOOL',
      type: 'categorical',
      classes: ['GP', 'MS'],
      values: [349, 46],
    },
    {
      name: 'SEX',
      type: 'categorical',
      classes: ['F', 'M'],
      values: [208, 187],
    },
    {
      name: 'AGE',
      type: 'numerical',
      min: 15,
      max: 22,
      classes: [15, 17, 19, 21, 22],
      values: [284, 106, 4, 1],
    },
    {
      name: 'ADDRESS',
      type: 'categorical',
      classes: ['U', 'R'],
      values: [307, 88],
    },
    {
      name: 'FAMSIZE',
      type: 'categorical',
      classes: ['GT3', 'LE3'],
      values: [281, 114],
    },
    {
      name: 'PSTATUS',
      type: 'categorical',
      classes: ['T', 'A'],
      values: [354, 41],
    },
    {
      name: 'MEDU',
      type: 'numerical',
      min: 0,
      max: 4,
      classes: [0, 1, 2, 3, 4],
      values: [131, 103, 99, 62],
    },
    {
      name: 'FEDU',
      type: 'numerical',
      min: 0,
      max: 4,
      classes: [0, 1, 2, 3, 4],
      values: [115, 100, 96, 84],
    },
    {
      name: 'MJOB',
      type: 'categorical',
      classes: ['other', 'services', 'at_home', 'teacher', 'health'],
      values: [141, 103, 59, 58, 34],
    },
    {
      name: 'FJOB',
      type: 'categorical',
      classes: ['other', 'services', 'teacher', 'at_home', 'health'],
      values: [217, 111, 29, 20, 18],
    },
    {
      name: 'REASON',
      type: 'categorical',
      classes: ['course', 'home', 'reputation', 'other'],
      values: [145, 109, 105, 36],
    },
    {
      name: 'GUARDIAN',
      type: 'categorical',
      classes: ['mother', 'father', 'other'],
      values: [273, 90, 32],
    },
    {
      name: 'TRAVELTIME',
      type: 'numerical',
      min: 1,
      max: 4,
      classes: [1, 2, 3, 4],
      values: [364, 23, 8],
    },
    {
      name: 'STUDYTIME',
      type: 'numerical',
      min: 1,
      max: 4,
      classes: [1, 2, 3, 4],
      values: [303, 65, 27],
    },
    {
      name: 'FAILURES',
      type: 'numerical',
      min: 0,
      max: 3,
      classes: [0, 1, 2, 3],
      values: [362, 17, 16],
    },
    {
      name: 'SCHOOLSUP',
      type: 'categorical',
      classes: ['no', 'yes'],
      values: [344, 51],
    },
    {
      name: 'FAMSUP',
      type: 'categorical',
      classes: ['yes', 'no'],
      values: [242, 153],
    },
    {
      name: 'PAID',
      type: 'categorical',
      classes: ['no', 'yes'],
      values: [214, 181],
    },
    {
      name: 'ACTIVITIES',
      type: 'categorical',
      classes: ['yes', 'no'],
      values: [201, 194],
    },
    {
      name: 'NURSERY',
      type: 'categorical',
      classes: ['yes', 'no'],
      values: [314, 81],
    },
    {
      name: 'HIGHER',
      type: 'categorical',
      classes: ['yes', 'no'],
      values: [375, 20],
    },
    {
      name: 'INTERNET',
      type: 'categorical',
      classes: ['yes', 'no'],
      values: [329, 66],
    },
    {
      name: 'ROMANTIC',
      type: 'categorical',
      classes: ['no', 'yes'],
      values: [263, 132],
    },
    {
      name: 'FAMREL',
      type: 'numerical',
      min: 1,
      max: 5,
      classes: [1, 2, 3, 4, 5],
      values: [195, 106, 68, 26],
    },
    {
      name: 'FREETIME',
      type: 'numerical',
      min: 1,
      max: 5,
      classes: [1, 2, 3, 4, 5],
      values: [157, 115, 83, 40],
    },
    {
      name: 'GOOUT',
      type: 'numerical',
      min: 1,
      max: 5,
      classes: [1, 2, 3, 4, 5],
      values: [130, 126, 86, 53],
    },
    {
      name: 'DALC',
      type: 'numerical',
      min: 1,
      max: 5,
      classes: [1, 2, 3, 4, 5],
      values: [351, 26, 9, 9],
    },
    {
      name: 'WALC',
      type: 'numerical',
      min: 1,
      max: 5,
      classes: [1, 2, 3, 4, 5],
      values: [236, 80, 51, 28],
    },
    {
      name: 'HEALTH',
      type: 'numerical',
      min: 1,
      max: 5,
      classes: [1, 2, 3, 4, 5],
      values: [146, 92, 91, 66],
    },
    {
      name: 'ABSENCES',
      type: 'numerical',
      min: 0,
      max: 75,
      classes: [0, 19, 38, 57, 75],
      values: [376, 15, 3, 1],
    },
    {
      name: 'G1',
      type: 'numerical',
      min: 3,
      max: 19,
      classes: [3, 7, 11, 15, 19],
      values: [162, 122, 70, 41],
    },
    {
      name: 'G2',
      type: 'numerical',
      min: 0,
      max: 19,
      classes: [0, 5, 10, 15, 19],
      values: [170, 163, 33, 29],
    },
  ]);
